spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:33306/db?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: admin
    password: 123456
